### ISSUE TITLE
Animal Feeder and Small Animal Pen become solid green when highlighted

### ISSUE THREAD

**Issue by andykorth** [bnema/AnimalHusbandry_Eco#3]
When playing Eco 0.9.7.7 beta-431 with "Animal Husbandry (9.7+) for ECO, version 1.0.0, Dec 12th, 2022", I noticed that highlighting the animal feeder and small animal pen causes the entire object to become solid green, rather than getting a small green outline. 

I figured this might be something I could fix, but I didn't find the source for the Husbandry2.unity3d  asset bundle that contains the assets. Is that something we have? Or would be able to get access to from the original mod author?

My first thought is that it might be as simple as an incorrect check mark on a HighlightableObject component.

**Comment by andykorth** [comment]
In-game screenshot of the issue:
http://kortham.homeip.net/files/Eco_2023-02-01_21-56-18.jpg

The electric butcher table does not have this issue.

**Comment by bnema** [comment]
Hello !

The Husbandry2.unity3d is at the root path of the project : https://github.com/bnema/AnimalHusbandry_Eco/blob/main/Husbandry2.unity3d


I've seen this bug indeed, but I couldn't pin point what was causing this issue so since it was not game breaking i've just decided to let this as it is, feel free to do a PR !

**Comment by andykorth** [comment]
Sorry for being a bit unclear- I do have that file, but I need the original contents before it was packed into a bundle. I might be able to pull the meshes and textures out of the bundle, but I'd have to recreate all the prefabs. I did reach out to Mystra to see if they might have the originals. Then we can add the originals to the git repo and I can rebundle them as needed.

**Comment by andykorth** [comment]
Hey, I made a pull request for this issue here:
https://github.com/bnema/AnimalHusbandry_Eco/pull/4

Let me know if you have any questions or what your thoughts are. Sorry it required a fairly large change in terms of remaking the unity asset.

**Comment by bnema** [comment]
hey @andykorth i'm reopening this issue so to let you know that here is a bug related to your PR : https://github.com/bnema/AnimalHusbandry_Eco/issues/5

Since i'm no longer playing, i'll just undo the PR for now
